app:
  message: This is the property file for the ${spring.application.name} specific to DEV Environment

spring:
  application:
    name: customeronboarding
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/{vendor}/migration
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/customer?useSSL=false
    username: root
    password: Admin@123
    testOnBorrow: true
    testWhileIdle: true
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 30000
    validationQuery: SELECT 1
    max-active: 15
    max-idle: 10
    max-wait: 8000
  jpa:
    hibernate:
      properties:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        ddl-auto: validate
    show-sql: true

# Updated server properties to get a fixed custom port and also configure error message display
# at UI side
server:
  port: 9191
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: on_param
    include-exception: false